### ISSUE TITLE
Invalid offsets in branches should be detected by assembler not runtime

### ISSUE THREAD

**Issue by m1n1** [ThaumicMekanism/venusbackend#9]
Entering an offset that is not a multiple of 4 doesn't lead to an assembler error. Instead it will fail later. Detect those cases at assembly time.

I already skimmed through the code a little but I couldn't find an easy fix.
The Issue is not critial for us, but it would be a nice fix if it can be done with a reasonable amount of work.

**Comment by ThaumicMekanism** [comment]
A branch is allowed to jump to multiples of two since compressed instructions are supported. It is not possible to have an odd target so all branches produced are technically valid.
